# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    resource.player:
        parent:    "api.resource"
        arguments: [ "PingPong\\Player\\Player" ]
        tags:      [ { name: "api.resource" } ]
    resource.teams:
        parent:    "api.resource"
        arguments: [ "PingPong\\Team\\Team" ]
        tags:      [ { name: "api.resource" } ]
